/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdmRouteRouteImport } from './routes/_authenticated/_adm/route'
import { Route as AuthenticatedAssistenciasRouteImport } from './routes/_authenticated/assistencias'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedCentrosTrabalhoRouteImport } from './routes/_authenticated/centros-trabalho'
import { Route as AuthenticatedChaoFabricaRouteImport } from './routes/_authenticated/chao-fabrica'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedComponentesRouteImport } from './routes/_authenticated/componentes'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedContasPagarRouteImport } from './routes/_authenticated/contas-pagar'
import { Route as AuthenticatedContasReceberRouteImport } from './routes/_authenticated/contas-receber'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedEntreguePorReceberRouteImport } from './routes/_authenticated/entregue-por-receber'
import { Route as AuthenticatedEtapasProducaoRouteImport } from './routes/_authenticated/etapas-producao'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedMeuCaixaRouteImport } from './routes/_authenticated/meu-caixa'
import { Route as AuthenticatedMovimentosRouteImport } from './routes/_authenticated/movimentos'
import { Route as AuthenticatedNecessidadesRouteImport } from './routes/_authenticated/necessidades'
import { Route as AuthenticatedNecessidadesProducaoRouteImport } from './routes/_authenticated/necessidades-producao'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPedidosCompraRouteImport } from './routes/_authenticated/pedidos-compra'
import { Route as AuthenticatedPorAgendarRouteImport } from './routes/_authenticated/por-agendar'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedRecepcaoRouteImport } from './routes/_authenticated/recepcao'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedReservasRouteImport } from './routes/_authenticated/reservas'
import { Route as AuthenticatedRotaRouteImport } from './routes/_authenticated/rota'
import { Route as AuthenticatedRotaModelosRouteImport } from './routes/_authenticated/rota-modelos'
import { Route as AuthenticatedRoteirosRouteImport } from './routes/_authenticated/roteiros'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedViaturasRouteImport } from './routes/_authenticated/viaturas'
import { Route as AuthenticatedAdmCaixasRouteImport } from './routes/_authenticated/_adm/caixas'
import { Route as AuthenticatedAdmCalendarioRouteImport } from './routes/_authenticated/_adm/calendario'
import { Route as AuthenticatedAdmCupoesRouteImport } from './routes/_authenticated/_adm/cupoes'
import { Route as AuthenticatedAdmDefinicoesRouteImport } from './routes/_authenticated/_adm/definicoes'
import { Route as AuthenticatedAdmFormasPagamentoRouteImport } from './routes/_authenticated/_adm/formas-pagamento'
import { Route as AuthenticatedAdmHistoricoRouteImport } from './routes/_authenticated/_adm/historico'
import { Route as AuthenticatedAdmLixeiraRouteImport } from './routes/_authenticated/_adm/lixeira'
import { Route as AuthenticatedAdmMotivosRouteImport } from './routes/_authenticated/_adm/motivos'
import { Route as AuthenticatedAdmReconciliacaoRouteImport } from './routes/_authenticated/_adm/reconciliacao'
import { Route as AuthenticatedAdmRegrasDescontoRouteImport } from './routes/_authenticated/_adm/regras-desconto'
import { Route as AuthenticatedAdmSincronizacaoRouteImport } from './routes/_authenticated/_adm/sincronizacao'
import { Route as AuthenticatedAdmUtilizadoresRouteImport } from './routes/_authenticated/_adm/utilizadores'
import { Route as AuthenticatedAdmZonasEntregaRouteImport } from './routes/_authenticated/_adm/zonas-entrega'
import { Route as AuthenticatedOrdensCompraIndexRouteImport } from './routes/_authenticated/ordens-compra.index'
import { Route as AuthenticatedOrdensCompraOcIdRouteImport } from './routes/_authenticated/ordens-compra.$ocId'
import { Route as AuthenticatedOrdensProducaoIndexRouteImport } from './routes/_authenticated/ordens-producao.index'
import { Route as AuthenticatedOrdensProducaoOpIdRouteImport } from './routes/_authenticated/ordens-producao.$opId'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos.index'
import { Route as AuthenticatedPedidosPedidoIdRouteImport } from './routes/_authenticated/pedidos.$pedidoId'
import { Route as AuthenticatedPlanosProducaoIndexRouteImport } from './routes/_authenticated/planos-producao.index'
import { Route as AuthenticatedPlanosProducaoPlanoIdRouteImport } from './routes/_authenticated/planos-producao.$planoId'
import { Route as AuthenticatedRotasIndexRouteImport } from './routes/_authenticated/rotas.index'
import { Route as AuthenticatedRotasRotaIdRouteImport } from './routes/_authenticated/rotas.$rotaId'
import { Route as AuthenticatedStockIndexRouteImport } from './routes/_authenticated/stock.index'
import { Route as AuthenticatedStockProdutoIdRouteImport } from './routes/_authenticated/stock.$produtoId'
import { Route as ApiPublicHooksSyncContagemRouteImport } from './routes/api/public/hooks/sync-contagem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdmRouteRoute = AuthenticatedAdmRouteRouteImport.update({
  id: '/_adm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistenciasRoute =
  AuthenticatedAssistenciasRouteImport.update({
    id: '/assistencias',
    path: '/assistencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCentrosTrabalhoRoute =
  AuthenticatedCentrosTrabalhoRouteImport.update({
    id: '/centros-trabalho',
    path: '/centros-trabalho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChaoFabricaRoute =
  AuthenticatedChaoFabricaRouteImport.update({
    id: '/chao-fabrica',
    path: '/chao-fabrica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComponentesRoute =
  AuthenticatedComponentesRouteImport.update({
    id: '/componentes',
    path: '/componentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasPagarRoute =
  AuthenticatedContasPagarRouteImport.update({
    id: '/contas-pagar',
    path: '/contas-pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasReceberRoute =
  AuthenticatedContasReceberRouteImport.update({
    id: '/contas-receber',
    path: '/contas-receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntreguePorReceberRoute =
  AuthenticatedEntreguePorReceberRouteImport.update({
    id: '/entregue-por-receber',
    path: '/entregue-por-receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEtapasProducaoRoute =
  AuthenticatedEtapasProducaoRouteImport.update({
    id: '/etapas-producao',
    path: '/etapas-producao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeuCaixaRoute = AuthenticatedMeuCaixaRouteImport.update({
  id: '/meu-caixa',
  path: '/meu-caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentosRoute = AuthenticatedMovimentosRouteImport.update({
  id: '/movimentos',
  path: '/movimentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNecessidadesRoute =
  AuthenticatedNecessidadesRouteImport.update({
    id: '/necessidades',
    path: '/necessidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNecessidadesProducaoRoute =
  AuthenticatedNecessidadesProducaoRouteImport.update({
    id: '/necessidades-producao',
    path: '/necessidades-producao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosCompraRoute =
  AuthenticatedPedidosCompraRouteImport.update({
    id: '/pedidos-compra',
    path: '/pedidos-compra',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPorAgendarRoute = AuthenticatedPorAgendarRouteImport.update({
  id: '/por-agendar',
  path: '/por-agendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecepcaoRoute = AuthenticatedRecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservasRoute = AuthenticatedReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotaRoute = AuthenticatedRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotaModelosRoute =
  AuthenticatedRotaModelosRouteImport.update({
    id: '/rota-modelos',
    path: '/rota-modelos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoteirosRoute = AuthenticatedRoteirosRouteImport.update({
  id: '/roteiros',
  path: '/roteiros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViaturasRoute = AuthenticatedViaturasRouteImport.update({
  id: '/viaturas',
  path: '/viaturas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdmCaixasRoute = AuthenticatedAdmCaixasRouteImport.update({
  id: '/caixas',
  path: '/caixas',
  getParentRoute: () => AuthenticatedAdmRouteRoute,
} as any)
const AuthenticatedAdmCalendarioRoute =
  AuthenticatedAdmCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmCupoesRoute = AuthenticatedAdmCupoesRouteImport.update({
  id: '/cupoes',
  path: '/cupoes',
  getParentRoute: () => AuthenticatedAdmRouteRoute,
} as any)
const AuthenticatedAdmDefinicoesRoute =
  AuthenticatedAdmDefinicoesRouteImport.update({
    id: '/definicoes',
    path: '/definicoes',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmFormasPagamentoRoute =
  AuthenticatedAdmFormasPagamentoRouteImport.update({
    id: '/formas-pagamento',
    path: '/formas-pagamento',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmHistoricoRoute =
  AuthenticatedAdmHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmLixeiraRoute = AuthenticatedAdmLixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => AuthenticatedAdmRouteRoute,
} as any)
const AuthenticatedAdmMotivosRoute = AuthenticatedAdmMotivosRouteImport.update({
  id: '/motivos',
  path: '/motivos',
  getParentRoute: () => AuthenticatedAdmRouteRoute,
} as any)
const AuthenticatedAdmReconciliacaoRoute =
  AuthenticatedAdmReconciliacaoRouteImport.update({
    id: '/reconciliacao',
    path: '/reconciliacao',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmRegrasDescontoRoute =
  AuthenticatedAdmRegrasDescontoRouteImport.update({
    id: '/regras-desconto',
    path: '/regras-desconto',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmSincronizacaoRoute =
  AuthenticatedAdmSincronizacaoRouteImport.update({
    id: '/sincronizacao',
    path: '/sincronizacao',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmUtilizadoresRoute =
  AuthenticatedAdmUtilizadoresRouteImport.update({
    id: '/utilizadores',
    path: '/utilizadores',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmZonasEntregaRoute =
  AuthenticatedAdmZonasEntregaRouteImport.update({
    id: '/zonas-entrega',
    path: '/zonas-entrega',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedOrdensCompraIndexRoute =
  AuthenticatedOrdensCompraIndexRouteImport.update({
    id: '/ordens-compra/',
    path: '/ordens-compra/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdensCompraOcIdRoute =
  AuthenticatedOrdensCompraOcIdRouteImport.update({
    id: '/ordens-compra/$ocId',
    path: '/ordens-compra/$ocId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdensProducaoIndexRoute =
  AuthenticatedOrdensProducaoIndexRouteImport.update({
    id: '/ordens-producao/',
    path: '/ordens-producao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdensProducaoOpIdRoute =
  AuthenticatedOrdensProducaoOpIdRouteImport.update({
    id: '/ordens-producao/$opId',
    path: '/ordens-producao/$opId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosPedidoIdRoute =
  AuthenticatedPedidosPedidoIdRouteImport.update({
    id: '/pedidos/$pedidoId',
    path: '/pedidos/$pedidoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanosProducaoIndexRoute =
  AuthenticatedPlanosProducaoIndexRouteImport.update({
    id: '/planos-producao/',
    path: '/planos-producao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanosProducaoPlanoIdRoute =
  AuthenticatedPlanosProducaoPlanoIdRouteImport.update({
    id: '/planos-producao/$planoId',
    path: '/planos-producao/$planoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotasIndexRoute = AuthenticatedRotasIndexRouteImport.update({
  id: '/rotas/',
  path: '/rotas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotasRotaIdRoute =
  AuthenticatedRotasRotaIdRouteImport.update({
    id: '/rotas/$rotaId',
    path: '/rotas/$rotaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockIndexRoute = AuthenticatedStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockProdutoIdRoute =
  AuthenticatedStockProdutoIdRouteImport.update({
    id: '/stock/$produtoId',
    path: '/stock/$produtoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksSyncContagemRoute =
  ApiPublicHooksSyncContagemRouteImport.update({
    id: '/api/public/hooks/sync-contagem',
    path: '/api/public/hooks/sync-contagem',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistencias': typeof AuthenticatedAssistenciasRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/centros-trabalho': typeof AuthenticatedCentrosTrabalhoRoute
  '/chao-fabrica': typeof AuthenticatedChaoFabricaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/componentes': typeof AuthenticatedComponentesRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/entregue-por-receber': typeof AuthenticatedEntreguePorReceberRoute
  '/etapas-producao': typeof AuthenticatedEtapasProducaoRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/meu-caixa': typeof AuthenticatedMeuCaixaRoute
  '/movimentos': typeof AuthenticatedMovimentosRoute
  '/necessidades': typeof AuthenticatedNecessidadesRoute
  '/necessidades-producao': typeof AuthenticatedNecessidadesProducaoRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos-compra': typeof AuthenticatedPedidosCompraRoute
  '/por-agendar': typeof AuthenticatedPorAgendarRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/recepcao': typeof AuthenticatedRecepcaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/rota': typeof AuthenticatedRotaRoute
  '/rota-modelos': typeof AuthenticatedRotaModelosRoute
  '/roteiros': typeof AuthenticatedRoteirosRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/viaturas': typeof AuthenticatedViaturasRoute
  '/caixas': typeof AuthenticatedAdmCaixasRoute
  '/calendario': typeof AuthenticatedAdmCalendarioRoute
  '/cupoes': typeof AuthenticatedAdmCupoesRoute
  '/definicoes': typeof AuthenticatedAdmDefinicoesRoute
  '/formas-pagamento': typeof AuthenticatedAdmFormasPagamentoRoute
  '/historico': typeof AuthenticatedAdmHistoricoRoute
  '/lixeira': typeof AuthenticatedAdmLixeiraRoute
  '/motivos': typeof AuthenticatedAdmMotivosRoute
  '/reconciliacao': typeof AuthenticatedAdmReconciliacaoRoute
  '/regras-desconto': typeof AuthenticatedAdmRegrasDescontoRoute
  '/sincronizacao': typeof AuthenticatedAdmSincronizacaoRoute
  '/utilizadores': typeof AuthenticatedAdmUtilizadoresRoute
  '/zonas-entrega': typeof AuthenticatedAdmZonasEntregaRoute
  '/ordens-compra/$ocId': typeof AuthenticatedOrdensCompraOcIdRoute
  '/ordens-producao/$opId': typeof AuthenticatedOrdensProducaoOpIdRoute
  '/pedidos/$pedidoId': typeof AuthenticatedPedidosPedidoIdRoute
  '/planos-producao/$planoId': typeof AuthenticatedPlanosProducaoPlanoIdRoute
  '/rotas/$rotaId': typeof AuthenticatedRotasRotaIdRoute
  '/stock/$produtoId': typeof AuthenticatedStockProdutoIdRoute
  '/ordens-compra/': typeof AuthenticatedOrdensCompraIndexRoute
  '/ordens-producao/': typeof AuthenticatedOrdensProducaoIndexRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/planos-producao/': typeof AuthenticatedPlanosProducaoIndexRoute
  '/rotas/': typeof AuthenticatedRotasIndexRoute
  '/stock/': typeof AuthenticatedStockIndexRoute
  '/api/public/hooks/sync-contagem': typeof ApiPublicHooksSyncContagemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assistencias': typeof AuthenticatedAssistenciasRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/centros-trabalho': typeof AuthenticatedCentrosTrabalhoRoute
  '/chao-fabrica': typeof AuthenticatedChaoFabricaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/componentes': typeof AuthenticatedComponentesRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/entregue-por-receber': typeof AuthenticatedEntreguePorReceberRoute
  '/etapas-producao': typeof AuthenticatedEtapasProducaoRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/meu-caixa': typeof AuthenticatedMeuCaixaRoute
  '/movimentos': typeof AuthenticatedMovimentosRoute
  '/necessidades': typeof AuthenticatedNecessidadesRoute
  '/necessidades-producao': typeof AuthenticatedNecessidadesProducaoRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos-compra': typeof AuthenticatedPedidosCompraRoute
  '/por-agendar': typeof AuthenticatedPorAgendarRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/recepcao': typeof AuthenticatedRecepcaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/rota': typeof AuthenticatedRotaRoute
  '/rota-modelos': typeof AuthenticatedRotaModelosRoute
  '/roteiros': typeof AuthenticatedRoteirosRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/viaturas': typeof AuthenticatedViaturasRoute
  '/caixas': typeof AuthenticatedAdmCaixasRoute
  '/calendario': typeof AuthenticatedAdmCalendarioRoute
  '/cupoes': typeof AuthenticatedAdmCupoesRoute
  '/definicoes': typeof AuthenticatedAdmDefinicoesRoute
  '/formas-pagamento': typeof AuthenticatedAdmFormasPagamentoRoute
  '/historico': typeof AuthenticatedAdmHistoricoRoute
  '/lixeira': typeof AuthenticatedAdmLixeiraRoute
  '/motivos': typeof AuthenticatedAdmMotivosRoute
  '/reconciliacao': typeof AuthenticatedAdmReconciliacaoRoute
  '/regras-desconto': typeof AuthenticatedAdmRegrasDescontoRoute
  '/sincronizacao': typeof AuthenticatedAdmSincronizacaoRoute
  '/utilizadores': typeof AuthenticatedAdmUtilizadoresRoute
  '/zonas-entrega': typeof AuthenticatedAdmZonasEntregaRoute
  '/ordens-compra/$ocId': typeof AuthenticatedOrdensCompraOcIdRoute
  '/ordens-producao/$opId': typeof AuthenticatedOrdensProducaoOpIdRoute
  '/pedidos/$pedidoId': typeof AuthenticatedPedidosPedidoIdRoute
  '/planos-producao/$planoId': typeof AuthenticatedPlanosProducaoPlanoIdRoute
  '/rotas/$rotaId': typeof AuthenticatedRotasRotaIdRoute
  '/stock/$produtoId': typeof AuthenticatedStockProdutoIdRoute
  '/ordens-compra': typeof AuthenticatedOrdensCompraIndexRoute
  '/ordens-producao': typeof AuthenticatedOrdensProducaoIndexRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
  '/planos-producao': typeof AuthenticatedPlanosProducaoIndexRoute
  '/rotas': typeof AuthenticatedRotasIndexRoute
  '/stock': typeof AuthenticatedStockIndexRoute
  '/api/public/hooks/sync-contagem': typeof ApiPublicHooksSyncContagemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_adm': typeof AuthenticatedAdmRouteRouteWithChildren
  '/_authenticated/assistencias': typeof AuthenticatedAssistenciasRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/centros-trabalho': typeof AuthenticatedCentrosTrabalhoRoute
  '/_authenticated/chao-fabrica': typeof AuthenticatedChaoFabricaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/componentes': typeof AuthenticatedComponentesRoute
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/_authenticated/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/_authenticated/contas-receber': typeof AuthenticatedContasReceberRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/entregue-por-receber': typeof AuthenticatedEntreguePorReceberRoute
  '/_authenticated/etapas-producao': typeof AuthenticatedEtapasProducaoRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/meu-caixa': typeof AuthenticatedMeuCaixaRoute
  '/_authenticated/movimentos': typeof AuthenticatedMovimentosRoute
  '/_authenticated/necessidades': typeof AuthenticatedNecessidadesRoute
  '/_authenticated/necessidades-producao': typeof AuthenticatedNecessidadesProducaoRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pedidos-compra': typeof AuthenticatedPedidosCompraRoute
  '/_authenticated/por-agendar': typeof AuthenticatedPorAgendarRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/recepcao': typeof AuthenticatedRecepcaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/reservas': typeof AuthenticatedReservasRoute
  '/_authenticated/rota': typeof AuthenticatedRotaRoute
  '/_authenticated/rota-modelos': typeof AuthenticatedRotaModelosRoute
  '/_authenticated/roteiros': typeof AuthenticatedRoteirosRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/viaturas': typeof AuthenticatedViaturasRoute
  '/_authenticated/_adm/caixas': typeof AuthenticatedAdmCaixasRoute
  '/_authenticated/_adm/calendario': typeof AuthenticatedAdmCalendarioRoute
  '/_authenticated/_adm/cupoes': typeof AuthenticatedAdmCupoesRoute
  '/_authenticated/_adm/definicoes': typeof AuthenticatedAdmDefinicoesRoute
  '/_authenticated/_adm/formas-pagamento': typeof AuthenticatedAdmFormasPagamentoRoute
  '/_authenticated/_adm/historico': typeof AuthenticatedAdmHistoricoRoute
  '/_authenticated/_adm/lixeira': typeof AuthenticatedAdmLixeiraRoute
  '/_authenticated/_adm/motivos': typeof AuthenticatedAdmMotivosRoute
  '/_authenticated/_adm/reconciliacao': typeof AuthenticatedAdmReconciliacaoRoute
  '/_authenticated/_adm/regras-desconto': typeof AuthenticatedAdmRegrasDescontoRoute
  '/_authenticated/_adm/sincronizacao': typeof AuthenticatedAdmSincronizacaoRoute
  '/_authenticated/_adm/utilizadores': typeof AuthenticatedAdmUtilizadoresRoute
  '/_authenticated/_adm/zonas-entrega': typeof AuthenticatedAdmZonasEntregaRoute
  '/_authenticated/ordens-compra/$ocId': typeof AuthenticatedOrdensCompraOcIdRoute
  '/_authenticated/ordens-producao/$opId': typeof AuthenticatedOrdensProducaoOpIdRoute
  '/_authenticated/pedidos/$pedidoId': typeof AuthenticatedPedidosPedidoIdRoute
  '/_authenticated/planos-producao/$planoId': typeof AuthenticatedPlanosProducaoPlanoIdRoute
  '/_authenticated/rotas/$rotaId': typeof AuthenticatedRotasRotaIdRoute
  '/_authenticated/stock/$produtoId': typeof AuthenticatedStockProdutoIdRoute
  '/_authenticated/ordens-compra/': typeof AuthenticatedOrdensCompraIndexRoute
  '/_authenticated/ordens-producao/': typeof AuthenticatedOrdensProducaoIndexRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/_authenticated/planos-producao/': typeof AuthenticatedPlanosProducaoIndexRoute
  '/_authenticated/rotas/': typeof AuthenticatedRotasIndexRoute
  '/_authenticated/stock/': typeof AuthenticatedStockIndexRoute
  '/api/public/hooks/sync-contagem': typeof ApiPublicHooksSyncContagemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistencias'
    | '/caixa'
    | '/categorias'
    | '/centros-trabalho'
    | '/chao-fabrica'
    | '/clientes'
    | '/componentes'
    | '/conciliacao'
    | '/contas-pagar'
    | '/contas-receber'
    | '/despesas'
    | '/entregas'
    | '/entregue-por-receber'
    | '/etapas-producao'
    | '/fornecedores'
    | '/meu-caixa'
    | '/movimentos'
    | '/necessidades'
    | '/necessidades-producao'
    | '/pagamentos'
    | '/painel'
    | '/pedidos-compra'
    | '/por-agendar'
    | '/produtos'
    | '/recepcao'
    | '/relatorios'
    | '/reservas'
    | '/rota'
    | '/rota-modelos'
    | '/roteiros'
    | '/servicos'
    | '/viaturas'
    | '/caixas'
    | '/calendario'
    | '/cupoes'
    | '/definicoes'
    | '/formas-pagamento'
    | '/historico'
    | '/lixeira'
    | '/motivos'
    | '/reconciliacao'
    | '/regras-desconto'
    | '/sincronizacao'
    | '/utilizadores'
    | '/zonas-entrega'
    | '/ordens-compra/$ocId'
    | '/ordens-producao/$opId'
    | '/pedidos/$pedidoId'
    | '/planos-producao/$planoId'
    | '/rotas/$rotaId'
    | '/stock/$produtoId'
    | '/ordens-compra/'
    | '/ordens-producao/'
    | '/pedidos/'
    | '/planos-producao/'
    | '/rotas/'
    | '/stock/'
    | '/api/public/hooks/sync-contagem'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assistencias'
    | '/caixa'
    | '/categorias'
    | '/centros-trabalho'
    | '/chao-fabrica'
    | '/clientes'
    | '/componentes'
    | '/conciliacao'
    | '/contas-pagar'
    | '/contas-receber'
    | '/despesas'
    | '/entregas'
    | '/entregue-por-receber'
    | '/etapas-producao'
    | '/fornecedores'
    | '/meu-caixa'
    | '/movimentos'
    | '/necessidades'
    | '/necessidades-producao'
    | '/pagamentos'
    | '/painel'
    | '/pedidos-compra'
    | '/por-agendar'
    | '/produtos'
    | '/recepcao'
    | '/relatorios'
    | '/reservas'
    | '/rota'
    | '/rota-modelos'
    | '/roteiros'
    | '/servicos'
    | '/viaturas'
    | '/caixas'
    | '/calendario'
    | '/cupoes'
    | '/definicoes'
    | '/formas-pagamento'
    | '/historico'
    | '/lixeira'
    | '/motivos'
    | '/reconciliacao'
    | '/regras-desconto'
    | '/sincronizacao'
    | '/utilizadores'
    | '/zonas-entrega'
    | '/ordens-compra/$ocId'
    | '/ordens-producao/$opId'
    | '/pedidos/$pedidoId'
    | '/planos-producao/$planoId'
    | '/rotas/$rotaId'
    | '/stock/$produtoId'
    | '/ordens-compra'
    | '/ordens-producao'
    | '/pedidos'
    | '/planos-producao'
    | '/rotas'
    | '/stock'
    | '/api/public/hooks/sync-contagem'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_adm'
    | '/_authenticated/assistencias'
    | '/_authenticated/caixa'
    | '/_authenticated/categorias'
    | '/_authenticated/centros-trabalho'
    | '/_authenticated/chao-fabrica'
    | '/_authenticated/clientes'
    | '/_authenticated/componentes'
    | '/_authenticated/conciliacao'
    | '/_authenticated/contas-pagar'
    | '/_authenticated/contas-receber'
    | '/_authenticated/despesas'
    | '/_authenticated/entregas'
    | '/_authenticated/entregue-por-receber'
    | '/_authenticated/etapas-producao'
    | '/_authenticated/fornecedores'
    | '/_authenticated/meu-caixa'
    | '/_authenticated/movimentos'
    | '/_authenticated/necessidades'
    | '/_authenticated/necessidades-producao'
    | '/_authenticated/pagamentos'
    | '/_authenticated/painel'
    | '/_authenticated/pedidos-compra'
    | '/_authenticated/por-agendar'
    | '/_authenticated/produtos'
    | '/_authenticated/recepcao'
    | '/_authenticated/relatorios'
    | '/_authenticated/reservas'
    | '/_authenticated/rota'
    | '/_authenticated/rota-modelos'
    | '/_authenticated/roteiros'
    | '/_authenticated/servicos'
    | '/_authenticated/viaturas'
    | '/_authenticated/_adm/caixas'
    | '/_authenticated/_adm/calendario'
    | '/_authenticated/_adm/cupoes'
    | '/_authenticated/_adm/definicoes'
    | '/_authenticated/_adm/formas-pagamento'
    | '/_authenticated/_adm/historico'
    | '/_authenticated/_adm/lixeira'
    | '/_authenticated/_adm/motivos'
    | '/_authenticated/_adm/reconciliacao'
    | '/_authenticated/_adm/regras-desconto'
    | '/_authenticated/_adm/sincronizacao'
    | '/_authenticated/_adm/utilizadores'
    | '/_authenticated/_adm/zonas-entrega'
    | '/_authenticated/ordens-compra/$ocId'
    | '/_authenticated/ordens-producao/$opId'
    | '/_authenticated/pedidos/$pedidoId'
    | '/_authenticated/planos-producao/$planoId'
    | '/_authenticated/rotas/$rotaId'
    | '/_authenticated/stock/$produtoId'
    | '/_authenticated/ordens-compra/'
    | '/_authenticated/ordens-producao/'
    | '/_authenticated/pedidos/'
    | '/_authenticated/planos-producao/'
    | '/_authenticated/rotas/'
    | '/_authenticated/stock/'
    | '/api/public/hooks/sync-contagem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksSyncContagemRoute: typeof ApiPublicHooksSyncContagemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_adm': {
      id: '/_authenticated/_adm'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdmRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistencias': {
      id: '/_authenticated/assistencias'
      path: '/assistencias'
      fullPath: '/assistencias'
      preLoaderRoute: typeof AuthenticatedAssistenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-trabalho': {
      id: '/_authenticated/centros-trabalho'
      path: '/centros-trabalho'
      fullPath: '/centros-trabalho'
      preLoaderRoute: typeof AuthenticatedCentrosTrabalhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chao-fabrica': {
      id: '/_authenticated/chao-fabrica'
      path: '/chao-fabrica'
      fullPath: '/chao-fabrica'
      preLoaderRoute: typeof AuthenticatedChaoFabricaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/componentes': {
      id: '/_authenticated/componentes'
      path: '/componentes'
      fullPath: '/componentes'
      preLoaderRoute: typeof AuthenticatedComponentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-pagar': {
      id: '/_authenticated/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/contas-pagar'
      preLoaderRoute: typeof AuthenticatedContasPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-receber': {
      id: '/_authenticated/contas-receber'
      path: '/contas-receber'
      fullPath: '/contas-receber'
      preLoaderRoute: typeof AuthenticatedContasReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregue-por-receber': {
      id: '/_authenticated/entregue-por-receber'
      path: '/entregue-por-receber'
      fullPath: '/entregue-por-receber'
      preLoaderRoute: typeof AuthenticatedEntreguePorReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etapas-producao': {
      id: '/_authenticated/etapas-producao'
      path: '/etapas-producao'
      fullPath: '/etapas-producao'
      preLoaderRoute: typeof AuthenticatedEtapasProducaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-caixa': {
      id: '/_authenticated/meu-caixa'
      path: '/meu-caixa'
      fullPath: '/meu-caixa'
      preLoaderRoute: typeof AuthenticatedMeuCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentos': {
      id: '/_authenticated/movimentos'
      path: '/movimentos'
      fullPath: '/movimentos'
      preLoaderRoute: typeof AuthenticatedMovimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/necessidades': {
      id: '/_authenticated/necessidades'
      path: '/necessidades'
      fullPath: '/necessidades'
      preLoaderRoute: typeof AuthenticatedNecessidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/necessidades-producao': {
      id: '/_authenticated/necessidades-producao'
      path: '/necessidades-producao'
      fullPath: '/necessidades-producao'
      preLoaderRoute: typeof AuthenticatedNecessidadesProducaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos-compra': {
      id: '/_authenticated/pedidos-compra'
      path: '/pedidos-compra'
      fullPath: '/pedidos-compra'
      preLoaderRoute: typeof AuthenticatedPedidosCompraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/por-agendar': {
      id: '/_authenticated/por-agendar'
      path: '/por-agendar'
      fullPath: '/por-agendar'
      preLoaderRoute: typeof AuthenticatedPorAgendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recepcao': {
      id: '/_authenticated/recepcao'
      path: '/recepcao'
      fullPath: '/recepcao'
      preLoaderRoute: typeof AuthenticatedRecepcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservas': {
      id: '/_authenticated/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AuthenticatedReservasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota': {
      id: '/_authenticated/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof AuthenticatedRotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota-modelos': {
      id: '/_authenticated/rota-modelos'
      path: '/rota-modelos'
      fullPath: '/rota-modelos'
      preLoaderRoute: typeof AuthenticatedRotaModelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roteiros': {
      id: '/_authenticated/roteiros'
      path: '/roteiros'
      fullPath: '/roteiros'
      preLoaderRoute: typeof AuthenticatedRoteirosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viaturas': {
      id: '/_authenticated/viaturas'
      path: '/viaturas'
      fullPath: '/viaturas'
      preLoaderRoute: typeof AuthenticatedViaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_adm/caixas': {
      id: '/_authenticated/_adm/caixas'
      path: '/caixas'
      fullPath: '/caixas'
      preLoaderRoute: typeof AuthenticatedAdmCaixasRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/calendario': {
      id: '/_authenticated/_adm/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedAdmCalendarioRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/cupoes': {
      id: '/_authenticated/_adm/cupoes'
      path: '/cupoes'
      fullPath: '/cupoes'
      preLoaderRoute: typeof AuthenticatedAdmCupoesRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/definicoes': {
      id: '/_authenticated/_adm/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof AuthenticatedAdmDefinicoesRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/formas-pagamento': {
      id: '/_authenticated/_adm/formas-pagamento'
      path: '/formas-pagamento'
      fullPath: '/formas-pagamento'
      preLoaderRoute: typeof AuthenticatedAdmFormasPagamentoRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/historico': {
      id: '/_authenticated/_adm/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedAdmHistoricoRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/lixeira': {
      id: '/_authenticated/_adm/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof AuthenticatedAdmLixeiraRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/motivos': {
      id: '/_authenticated/_adm/motivos'
      path: '/motivos'
      fullPath: '/motivos'
      preLoaderRoute: typeof AuthenticatedAdmMotivosRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/reconciliacao': {
      id: '/_authenticated/_adm/reconciliacao'
      path: '/reconciliacao'
      fullPath: '/reconciliacao'
      preLoaderRoute: typeof AuthenticatedAdmReconciliacaoRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/regras-desconto': {
      id: '/_authenticated/_adm/regras-desconto'
      path: '/regras-desconto'
      fullPath: '/regras-desconto'
      preLoaderRoute: typeof AuthenticatedAdmRegrasDescontoRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/sincronizacao': {
      id: '/_authenticated/_adm/sincronizacao'
      path: '/sincronizacao'
      fullPath: '/sincronizacao'
      preLoaderRoute: typeof AuthenticatedAdmSincronizacaoRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/utilizadores': {
      id: '/_authenticated/_adm/utilizadores'
      path: '/utilizadores'
      fullPath: '/utilizadores'
      preLoaderRoute: typeof AuthenticatedAdmUtilizadoresRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/zonas-entrega': {
      id: '/_authenticated/_adm/zonas-entrega'
      path: '/zonas-entrega'
      fullPath: '/zonas-entrega'
      preLoaderRoute: typeof AuthenticatedAdmZonasEntregaRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/ordens-compra/': {
      id: '/_authenticated/ordens-compra/'
      path: '/ordens-compra'
      fullPath: '/ordens-compra/'
      preLoaderRoute: typeof AuthenticatedOrdensCompraIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens-compra/$ocId': {
      id: '/_authenticated/ordens-compra/$ocId'
      path: '/ordens-compra/$ocId'
      fullPath: '/ordens-compra/$ocId'
      preLoaderRoute: typeof AuthenticatedOrdensCompraOcIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens-producao/': {
      id: '/_authenticated/ordens-producao/'
      path: '/ordens-producao'
      fullPath: '/ordens-producao/'
      preLoaderRoute: typeof AuthenticatedOrdensProducaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens-producao/$opId': {
      id: '/_authenticated/ordens-producao/$opId'
      path: '/ordens-producao/$opId'
      fullPath: '/ordens-producao/$opId'
      preLoaderRoute: typeof AuthenticatedOrdensProducaoOpIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/$pedidoId': {
      id: '/_authenticated/pedidos/$pedidoId'
      path: '/pedidos/$pedidoId'
      fullPath: '/pedidos/$pedidoId'
      preLoaderRoute: typeof AuthenticatedPedidosPedidoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos-producao/': {
      id: '/_authenticated/planos-producao/'
      path: '/planos-producao'
      fullPath: '/planos-producao/'
      preLoaderRoute: typeof AuthenticatedPlanosProducaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos-producao/$planoId': {
      id: '/_authenticated/planos-producao/$planoId'
      path: '/planos-producao/$planoId'
      fullPath: '/planos-producao/$planoId'
      preLoaderRoute: typeof AuthenticatedPlanosProducaoPlanoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotas/': {
      id: '/_authenticated/rotas/'
      path: '/rotas'
      fullPath: '/rotas/'
      preLoaderRoute: typeof AuthenticatedRotasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotas/$rotaId': {
      id: '/_authenticated/rotas/$rotaId'
      path: '/rotas/$rotaId'
      fullPath: '/rotas/$rotaId'
      preLoaderRoute: typeof AuthenticatedRotasRotaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/': {
      id: '/_authenticated/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AuthenticatedStockIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/$produtoId': {
      id: '/_authenticated/stock/$produtoId'
      path: '/stock/$produtoId'
      fullPath: '/stock/$produtoId'
      preLoaderRoute: typeof AuthenticatedStockProdutoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/sync-contagem': {
      id: '/api/public/hooks/sync-contagem'
      path: '/api/public/hooks/sync-contagem'
      fullPath: '/api/public/hooks/sync-contagem'
      preLoaderRoute: typeof ApiPublicHooksSyncContagemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdmRouteRouteChildren {
  AuthenticatedAdmCaixasRoute: typeof AuthenticatedAdmCaixasRoute
  AuthenticatedAdmCalendarioRoute: typeof AuthenticatedAdmCalendarioRoute
  AuthenticatedAdmCupoesRoute: typeof AuthenticatedAdmCupoesRoute
  AuthenticatedAdmDefinicoesRoute: typeof AuthenticatedAdmDefinicoesRoute
  AuthenticatedAdmFormasPagamentoRoute: typeof AuthenticatedAdmFormasPagamentoRoute
  AuthenticatedAdmHistoricoRoute: typeof AuthenticatedAdmHistoricoRoute
  AuthenticatedAdmLixeiraRoute: typeof AuthenticatedAdmLixeiraRoute
  AuthenticatedAdmMotivosRoute: typeof AuthenticatedAdmMotivosRoute
  AuthenticatedAdmReconciliacaoRoute: typeof AuthenticatedAdmReconciliacaoRoute
  AuthenticatedAdmRegrasDescontoRoute: typeof AuthenticatedAdmRegrasDescontoRoute
  AuthenticatedAdmSincronizacaoRoute: typeof AuthenticatedAdmSincronizacaoRoute
  AuthenticatedAdmUtilizadoresRoute: typeof AuthenticatedAdmUtilizadoresRoute
  AuthenticatedAdmZonasEntregaRoute: typeof AuthenticatedAdmZonasEntregaRoute
}

const AuthenticatedAdmRouteRouteChildren: AuthenticatedAdmRouteRouteChildren = {
  AuthenticatedAdmCaixasRoute: AuthenticatedAdmCaixasRoute,
  AuthenticatedAdmCalendarioRoute: AuthenticatedAdmCalendarioRoute,
  AuthenticatedAdmCupoesRoute: AuthenticatedAdmCupoesRoute,
  AuthenticatedAdmDefinicoesRoute: AuthenticatedAdmDefinicoesRoute,
  AuthenticatedAdmFormasPagamentoRoute: AuthenticatedAdmFormasPagamentoRoute,
  AuthenticatedAdmHistoricoRoute: AuthenticatedAdmHistoricoRoute,
  AuthenticatedAdmLixeiraRoute: AuthenticatedAdmLixeiraRoute,
  AuthenticatedAdmMotivosRoute: AuthenticatedAdmMotivosRoute,
  AuthenticatedAdmReconciliacaoRoute: AuthenticatedAdmReconciliacaoRoute,
  AuthenticatedAdmRegrasDescontoRoute: AuthenticatedAdmRegrasDescontoRoute,
  AuthenticatedAdmSincronizacaoRoute: AuthenticatedAdmSincronizacaoRoute,
  AuthenticatedAdmUtilizadoresRoute: AuthenticatedAdmUtilizadoresRoute,
  AuthenticatedAdmZonasEntregaRoute: AuthenticatedAdmZonasEntregaRoute,
}

const AuthenticatedAdmRouteRouteWithChildren =
  AuthenticatedAdmRouteRoute._addFileChildren(
    AuthenticatedAdmRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdmRouteRoute: typeof AuthenticatedAdmRouteRouteWithChildren
  AuthenticatedAssistenciasRoute: typeof AuthenticatedAssistenciasRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedCentrosTrabalhoRoute: typeof AuthenticatedCentrosTrabalhoRoute
  AuthenticatedChaoFabricaRoute: typeof AuthenticatedChaoFabricaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComponentesRoute: typeof AuthenticatedComponentesRoute
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRoute
  AuthenticatedContasPagarRoute: typeof AuthenticatedContasPagarRoute
  AuthenticatedContasReceberRoute: typeof AuthenticatedContasReceberRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedEntreguePorReceberRoute: typeof AuthenticatedEntreguePorReceberRoute
  AuthenticatedEtapasProducaoRoute: typeof AuthenticatedEtapasProducaoRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedMeuCaixaRoute: typeof AuthenticatedMeuCaixaRoute
  AuthenticatedMovimentosRoute: typeof AuthenticatedMovimentosRoute
  AuthenticatedNecessidadesRoute: typeof AuthenticatedNecessidadesRoute
  AuthenticatedNecessidadesProducaoRoute: typeof AuthenticatedNecessidadesProducaoRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPedidosCompraRoute: typeof AuthenticatedPedidosCompraRoute
  AuthenticatedPorAgendarRoute: typeof AuthenticatedPorAgendarRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRecepcaoRoute: typeof AuthenticatedRecepcaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedReservasRoute: typeof AuthenticatedReservasRoute
  AuthenticatedRotaRoute: typeof AuthenticatedRotaRoute
  AuthenticatedRotaModelosRoute: typeof AuthenticatedRotaModelosRoute
  AuthenticatedRoteirosRoute: typeof AuthenticatedRoteirosRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedViaturasRoute: typeof AuthenticatedViaturasRoute
  AuthenticatedOrdensCompraOcIdRoute: typeof AuthenticatedOrdensCompraOcIdRoute
  AuthenticatedOrdensProducaoOpIdRoute: typeof AuthenticatedOrdensProducaoOpIdRoute
  AuthenticatedPedidosPedidoIdRoute: typeof AuthenticatedPedidosPedidoIdRoute
  AuthenticatedPlanosProducaoPlanoIdRoute: typeof AuthenticatedPlanosProducaoPlanoIdRoute
  AuthenticatedRotasRotaIdRoute: typeof AuthenticatedRotasRotaIdRoute
  AuthenticatedStockProdutoIdRoute: typeof AuthenticatedStockProdutoIdRoute
  AuthenticatedOrdensCompraIndexRoute: typeof AuthenticatedOrdensCompraIndexRoute
  AuthenticatedOrdensProducaoIndexRoute: typeof AuthenticatedOrdensProducaoIndexRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
  AuthenticatedPlanosProducaoIndexRoute: typeof AuthenticatedPlanosProducaoIndexRoute
  AuthenticatedRotasIndexRoute: typeof AuthenticatedRotasIndexRoute
  AuthenticatedStockIndexRoute: typeof AuthenticatedStockIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdmRouteRoute: AuthenticatedAdmRouteRouteWithChildren,
  AuthenticatedAssistenciasRoute: AuthenticatedAssistenciasRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedCentrosTrabalhoRoute: AuthenticatedCentrosTrabalhoRoute,
  AuthenticatedChaoFabricaRoute: AuthenticatedChaoFabricaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComponentesRoute: AuthenticatedComponentesRoute,
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRoute,
  AuthenticatedContasPagarRoute: AuthenticatedContasPagarRoute,
  AuthenticatedContasReceberRoute: AuthenticatedContasReceberRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedEntreguePorReceberRoute: AuthenticatedEntreguePorReceberRoute,
  AuthenticatedEtapasProducaoRoute: AuthenticatedEtapasProducaoRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedMeuCaixaRoute: AuthenticatedMeuCaixaRoute,
  AuthenticatedMovimentosRoute: AuthenticatedMovimentosRoute,
  AuthenticatedNecessidadesRoute: AuthenticatedNecessidadesRoute,
  AuthenticatedNecessidadesProducaoRoute:
    AuthenticatedNecessidadesProducaoRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPedidosCompraRoute: AuthenticatedPedidosCompraRoute,
  AuthenticatedPorAgendarRoute: AuthenticatedPorAgendarRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRecepcaoRoute: AuthenticatedRecepcaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedReservasRoute: AuthenticatedReservasRoute,
  AuthenticatedRotaRoute: AuthenticatedRotaRoute,
  AuthenticatedRotaModelosRoute: AuthenticatedRotaModelosRoute,
  AuthenticatedRoteirosRoute: AuthenticatedRoteirosRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedViaturasRoute: AuthenticatedViaturasRoute,
  AuthenticatedOrdensCompraOcIdRoute: AuthenticatedOrdensCompraOcIdRoute,
  AuthenticatedOrdensProducaoOpIdRoute: AuthenticatedOrdensProducaoOpIdRoute,
  AuthenticatedPedidosPedidoIdRoute: AuthenticatedPedidosPedidoIdRoute,
  AuthenticatedPlanosProducaoPlanoIdRoute:
    AuthenticatedPlanosProducaoPlanoIdRoute,
  AuthenticatedRotasRotaIdRoute: AuthenticatedRotasRotaIdRoute,
  AuthenticatedStockProdutoIdRoute: AuthenticatedStockProdutoIdRoute,
  AuthenticatedOrdensCompraIndexRoute: AuthenticatedOrdensCompraIndexRoute,
  AuthenticatedOrdensProducaoIndexRoute: AuthenticatedOrdensProducaoIndexRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
  AuthenticatedPlanosProducaoIndexRoute: AuthenticatedPlanosProducaoIndexRoute,
  AuthenticatedRotasIndexRoute: AuthenticatedRotasIndexRoute,
  AuthenticatedStockIndexRoute: AuthenticatedStockIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksSyncContagemRoute: ApiPublicHooksSyncContagemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
