/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdmRouteRouteImport } from './routes/_authenticated/_adm/route'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedAdmCalendarioRouteImport } from './routes/_authenticated/_adm/calendario'
import { Route as AuthenticatedAdmDefinicoesRouteImport } from './routes/_authenticated/_adm/definicoes'
import { Route as AuthenticatedAdmFormasPagamentoRouteImport } from './routes/_authenticated/_adm/formas-pagamento'
import { Route as AuthenticatedAdmHistoricoRouteImport } from './routes/_authenticated/_adm/historico'
import { Route as AuthenticatedAdmLixeiraRouteImport } from './routes/_authenticated/_adm/lixeira'
import { Route as AuthenticatedAdmMotivosRouteImport } from './routes/_authenticated/_adm/motivos'
import { Route as AuthenticatedAdmUtilizadoresRouteImport } from './routes/_authenticated/_adm/utilizadores'
import { Route as AuthenticatedAdmZonasEntregaRouteImport } from './routes/_authenticated/_adm/zonas-entrega'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdmRouteRoute = AuthenticatedAdmRouteRouteImport.update({
  id: '/_adm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdmCalendarioRoute =
  AuthenticatedAdmCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmDefinicoesRoute =
  AuthenticatedAdmDefinicoesRouteImport.update({
    id: '/definicoes',
    path: '/definicoes',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmFormasPagamentoRoute =
  AuthenticatedAdmFormasPagamentoRouteImport.update({
    id: '/formas-pagamento',
    path: '/formas-pagamento',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmHistoricoRoute =
  AuthenticatedAdmHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmLixeiraRoute = AuthenticatedAdmLixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => AuthenticatedAdmRouteRoute,
} as any)
const AuthenticatedAdmMotivosRoute = AuthenticatedAdmMotivosRouteImport.update({
  id: '/motivos',
  path: '/motivos',
  getParentRoute: () => AuthenticatedAdmRouteRoute,
} as any)
const AuthenticatedAdmUtilizadoresRoute =
  AuthenticatedAdmUtilizadoresRouteImport.update({
    id: '/utilizadores',
    path: '/utilizadores',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)
const AuthenticatedAdmZonasEntregaRoute =
  AuthenticatedAdmZonasEntregaRouteImport.update({
    id: '/zonas-entrega',
    path: '/zonas-entrega',
    getParentRoute: () => AuthenticatedAdmRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/calendario': typeof AuthenticatedAdmCalendarioRoute
  '/definicoes': typeof AuthenticatedAdmDefinicoesRoute
  '/formas-pagamento': typeof AuthenticatedAdmFormasPagamentoRoute
  '/historico': typeof AuthenticatedAdmHistoricoRoute
  '/lixeira': typeof AuthenticatedAdmLixeiraRoute
  '/motivos': typeof AuthenticatedAdmMotivosRoute
  '/utilizadores': typeof AuthenticatedAdmUtilizadoresRoute
  '/zonas-entrega': typeof AuthenticatedAdmZonasEntregaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/calendario': typeof AuthenticatedAdmCalendarioRoute
  '/definicoes': typeof AuthenticatedAdmDefinicoesRoute
  '/formas-pagamento': typeof AuthenticatedAdmFormasPagamentoRoute
  '/historico': typeof AuthenticatedAdmHistoricoRoute
  '/lixeira': typeof AuthenticatedAdmLixeiraRoute
  '/motivos': typeof AuthenticatedAdmMotivosRoute
  '/utilizadores': typeof AuthenticatedAdmUtilizadoresRoute
  '/zonas-entrega': typeof AuthenticatedAdmZonasEntregaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_adm': typeof AuthenticatedAdmRouteRouteWithChildren
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/_adm/calendario': typeof AuthenticatedAdmCalendarioRoute
  '/_authenticated/_adm/definicoes': typeof AuthenticatedAdmDefinicoesRoute
  '/_authenticated/_adm/formas-pagamento': typeof AuthenticatedAdmFormasPagamentoRoute
  '/_authenticated/_adm/historico': typeof AuthenticatedAdmHistoricoRoute
  '/_authenticated/_adm/lixeira': typeof AuthenticatedAdmLixeiraRoute
  '/_authenticated/_adm/motivos': typeof AuthenticatedAdmMotivosRoute
  '/_authenticated/_adm/utilizadores': typeof AuthenticatedAdmUtilizadoresRoute
  '/_authenticated/_adm/zonas-entrega': typeof AuthenticatedAdmZonasEntregaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categorias'
    | '/fornecedores'
    | '/painel'
    | '/produtos'
    | '/servicos'
    | '/calendario'
    | '/definicoes'
    | '/formas-pagamento'
    | '/historico'
    | '/lixeira'
    | '/motivos'
    | '/utilizadores'
    | '/zonas-entrega'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categorias'
    | '/fornecedores'
    | '/painel'
    | '/produtos'
    | '/servicos'
    | '/calendario'
    | '/definicoes'
    | '/formas-pagamento'
    | '/historico'
    | '/lixeira'
    | '/motivos'
    | '/utilizadores'
    | '/zonas-entrega'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_adm'
    | '/_authenticated/categorias'
    | '/_authenticated/fornecedores'
    | '/_authenticated/painel'
    | '/_authenticated/produtos'
    | '/_authenticated/servicos'
    | '/_authenticated/_adm/calendario'
    | '/_authenticated/_adm/definicoes'
    | '/_authenticated/_adm/formas-pagamento'
    | '/_authenticated/_adm/historico'
    | '/_authenticated/_adm/lixeira'
    | '/_authenticated/_adm/motivos'
    | '/_authenticated/_adm/utilizadores'
    | '/_authenticated/_adm/zonas-entrega'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_adm': {
      id: '/_authenticated/_adm'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdmRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_adm/calendario': {
      id: '/_authenticated/_adm/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedAdmCalendarioRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/definicoes': {
      id: '/_authenticated/_adm/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof AuthenticatedAdmDefinicoesRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/formas-pagamento': {
      id: '/_authenticated/_adm/formas-pagamento'
      path: '/formas-pagamento'
      fullPath: '/formas-pagamento'
      preLoaderRoute: typeof AuthenticatedAdmFormasPagamentoRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/historico': {
      id: '/_authenticated/_adm/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedAdmHistoricoRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/lixeira': {
      id: '/_authenticated/_adm/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof AuthenticatedAdmLixeiraRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/motivos': {
      id: '/_authenticated/_adm/motivos'
      path: '/motivos'
      fullPath: '/motivos'
      preLoaderRoute: typeof AuthenticatedAdmMotivosRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/utilizadores': {
      id: '/_authenticated/_adm/utilizadores'
      path: '/utilizadores'
      fullPath: '/utilizadores'
      preLoaderRoute: typeof AuthenticatedAdmUtilizadoresRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
    '/_authenticated/_adm/zonas-entrega': {
      id: '/_authenticated/_adm/zonas-entrega'
      path: '/zonas-entrega'
      fullPath: '/zonas-entrega'
      preLoaderRoute: typeof AuthenticatedAdmZonasEntregaRouteImport
      parentRoute: typeof AuthenticatedAdmRouteRoute
    }
  }
}

interface AuthenticatedAdmRouteRouteChildren {
  AuthenticatedAdmCalendarioRoute: typeof AuthenticatedAdmCalendarioRoute
  AuthenticatedAdmDefinicoesRoute: typeof AuthenticatedAdmDefinicoesRoute
  AuthenticatedAdmFormasPagamentoRoute: typeof AuthenticatedAdmFormasPagamentoRoute
  AuthenticatedAdmHistoricoRoute: typeof AuthenticatedAdmHistoricoRoute
  AuthenticatedAdmLixeiraRoute: typeof AuthenticatedAdmLixeiraRoute
  AuthenticatedAdmMotivosRoute: typeof AuthenticatedAdmMotivosRoute
  AuthenticatedAdmUtilizadoresRoute: typeof AuthenticatedAdmUtilizadoresRoute
  AuthenticatedAdmZonasEntregaRoute: typeof AuthenticatedAdmZonasEntregaRoute
}

const AuthenticatedAdmRouteRouteChildren: AuthenticatedAdmRouteRouteChildren = {
  AuthenticatedAdmCalendarioRoute: AuthenticatedAdmCalendarioRoute,
  AuthenticatedAdmDefinicoesRoute: AuthenticatedAdmDefinicoesRoute,
  AuthenticatedAdmFormasPagamentoRoute: AuthenticatedAdmFormasPagamentoRoute,
  AuthenticatedAdmHistoricoRoute: AuthenticatedAdmHistoricoRoute,
  AuthenticatedAdmLixeiraRoute: AuthenticatedAdmLixeiraRoute,
  AuthenticatedAdmMotivosRoute: AuthenticatedAdmMotivosRoute,
  AuthenticatedAdmUtilizadoresRoute: AuthenticatedAdmUtilizadoresRoute,
  AuthenticatedAdmZonasEntregaRoute: AuthenticatedAdmZonasEntregaRoute,
}

const AuthenticatedAdmRouteRouteWithChildren =
  AuthenticatedAdmRouteRoute._addFileChildren(
    AuthenticatedAdmRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdmRouteRoute: typeof AuthenticatedAdmRouteRouteWithChildren
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdmRouteRoute: AuthenticatedAdmRouteRouteWithChildren,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
